run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/mohammed-bageri/dockenv

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
