name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o build/dockenv-linux-amd64 .
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o build/dockenv-linux-arm64 .
          
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o build/dockenv-darwin-amd64 .
          
          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o build/dockenv-darwin-arm64 .
          
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o build/dockenv-windows-amd64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dockenv-linux-amd64
            build/dockenv-linux-arm64
            build/dockenv-darwin-amd64
            build/dockenv-darwin-arm64
            build/dockenv-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
